// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWbtfG9wzNkH92DEH5W9r0vedFQeO6TIc',
    appId: '1:165451780308:web:95c02904fbac2c1e4eab41',
    messagingSenderId: '165451780308',
    projectId: 'login-9cc2e',
    authDomain: 'login-9cc2e.firebaseapp.com',
    storageBucket: 'login-9cc2e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT80wjQBzY9P7vf_7tKrD5zsxY_Rz86aU',
    appId: '1:165451780308:android:4b61586c89a63b534eab41',
    messagingSenderId: '165451780308',
    projectId: 'login-9cc2e',
    storageBucket: 'login-9cc2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBazo4_Ld2viLr6vneDJ8gqGh1hYM0fpBg',
    appId: '1:165451780308:ios:f2a4cdd610cc803b4eab41',
    messagingSenderId: '165451780308',
    projectId: 'login-9cc2e',
    storageBucket: 'login-9cc2e.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBazo4_Ld2viLr6vneDJ8gqGh1hYM0fpBg',
    appId: '1:165451780308:ios:f2a4cdd610cc803b4eab41',
    messagingSenderId: '165451780308',
    projectId: 'login-9cc2e',
    storageBucket: 'login-9cc2e.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWbtfG9wzNkH92DEH5W9r0vedFQeO6TIc',
    appId: '1:165451780308:web:2acf67796a2c9cfa4eab41',
    messagingSenderId: '165451780308',
    projectId: 'login-9cc2e',
    authDomain: 'login-9cc2e.firebaseapp.com',
    storageBucket: 'login-9cc2e.appspot.com',
  );
}
